language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - pyrus channel-discover pear.symfony.com
  - pyrus install --force phpunit/DbUnit
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - travis-ci@kitpages.fr
